//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArventureAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class happening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public happening()
        {
            this.arventure = new HashSet<arventure>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public int idStory { get; set; }
    
        public virtual story story { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arventure> arventure { get; set; }
    }
}
