//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArventureAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class abp__politecnics_com_dam01Entities : DbContext
    {
        public abp__politecnics_com_dam01Entities()
            : base("name=abp__politecnics_com_dam01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<achievement> achievement { get; set; }
        public virtual DbSet<arventure> arventure { get; set; }
        public virtual DbSet<fragment> fragment { get; set; }
        public virtual DbSet<happening> happening { get; set; }
        public virtual DbSet<route> route { get; set; }
        public virtual DbSet<stop> stop { get; set; }
        public virtual DbSet<story> story { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
